### PR TITLE
Add hendragon curve and improve readme

### PR DESCRIPTION
**Pull request by HendrikRoehm**

### CODE REVIEW

**Comment by HendrikRoehm** [comment]
There is a need to document how the jupyter notebook can be executed with using the modules from src. I tried it via `jupyter notebook` and it did not work...

**Review by mschlund — APPROVED** [review]
lgtm

**Review by mschlund — COMMENTED** [review]
The curve has "holes" and is not space-filling right?

**Comment by HendrikRoehm** [comment]
@mschlund As you have approved the pr, you also should merge it. I do not have rights for that. ;)

Yes, after 5 iterations, one barely sees the curve and the holes become clear:
hendragon_curve

**Pull request merged**
